# Generated by Django 2.0.6 on 2018-07-03 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180703_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 13, 40, 21, 688742, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 13, 40, 21, 690184, tzinfo=utc), verbose_name='date published'),
        ),
    ]
