# Generated by Django 2.0.6 on 2018-07-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180706_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('custom_can_update_article', 'To provide update own article'),)},
        ),
    ]
